#!/bin/sh
#
# Create a basic virtual environment (sandox) for the weak Python server

python3 -m venv venv
venv/bin/pip3 install wheel
venv/bin/pip3 install --upgrade entrance

echo
echo To run, enter "./run"
echo